// pdfkit may need a dynamic import in ESM context
export async function generateTicket({ name, surname, age, sex, symptoms, triageLevel, rationale, instruction }) {
    const { default: PDFDocument } = await import('pdfkit')

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50, size: 'A4' })
        const chunks = []

        doc.on('data', (chunk) => chunks.push(chunk))
        doc.on('end', () => resolve(Buffer.concat(chunks)))
        doc.on('error', reject)

        // ── Header ──────────────────────────────────────────────
        doc
            .font('Helvetica-Bold')
            .fontSize(18)
            .fillColor('#0a0a12')
            .text('MEDAI EMERGENCY TRIAGE SYSTEM', { align: 'center' })
        doc.moveDown(0.3)
        doc
            .font('Helvetica')
            .fontSize(9)
            .fillColor('#888888')
            .text('AI-Powered Emergency Room Triage Report', { align: 'center' })
        doc.moveDown(0.3)
        doc
            .font('Helvetica')
            .fontSize(8)
            .fillColor('#aaaaaa')
            .text(`Generated: ${new Date().toISOString()}`, { align: 'center' })

        doc.moveDown(0.8)
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#dddddd')
        doc.moveDown(0.8)

        // ── Patient Info ─────────────────────────────────────────
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#888888').text('PATIENT INFORMATION')
        doc.moveDown(0.4)
        doc.font('Helvetica-Bold').fontSize(13).fillColor('#111111').text(`${name} ${surname}`)
        doc.moveDown(0.2)
        doc.font('Helvetica').fontSize(10).fillColor('#444444').text(`Age: ${age}  ·  Sex: ${sex}`)

        doc.moveDown(1)

        // ── Triage Level ─────────────────────────────────────────
        const colors = { CRITICAL: '#dc2626', URGENT: '#d97706', ROUTINE: '#059669' }
        const labels = {
            CRITICAL: '⬤  CRITICAL — IMMEDIATE ATTENTION',
            URGENT: '⬤  URGENT — PRIORITY CARE',
            ROUTINE: '⬤  ROUTINE — STANDARD QUEUE',
        }

        doc.font('Helvetica-Bold').fontSize(10).fillColor('#888888').text('TRIAGE CLASSIFICATION')
        doc.moveDown(0.4)
        doc
            .font('Helvetica-Bold')
            .fontSize(16)
            .fillColor(colors[triageLevel] ?? '#000000')
            .text(labels[triageLevel] ?? triageLevel)

        doc.moveDown(1)

        // ── Rationale ────────────────────────────────────────────
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#888888').text('AI RATIONALE')
        doc.moveDown(0.4)
        doc
            .font('Helvetica')
            .fontSize(10)
            .fillColor('#333333')
            .text(rationale, { width: 495, lineGap: 4 })

        doc.moveDown(1)

        // ── Patient Instruction ──────────────────────────────────
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#888888').text('PATIENT INSTRUCTION')
        doc.moveDown(0.4)

        // Draw a subtle background box for instruction
        const instrY = doc.y
        doc
            .font('Helvetica-Oblique')
            .fontSize(10)
            .fillColor('#222222')
            .text(instruction, 60, instrY, { width: 475, lineGap: 4 })

        doc.moveDown(1)

        // ── Reported Symptoms ────────────────────────────────────
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#888888').text('REPORTED SYMPTOMS')
        doc.moveDown(0.4)
        doc
            .font('Helvetica')
            .fontSize(10)
            .fillColor('#333333')
            .text(symptoms, { width: 495, lineGap: 3 })

        doc.moveDown(2)
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#dddddd')
        doc.moveDown(0.5)

        // ── Footer ───────────────────────────────────────────────
        doc
            .font('Helvetica')
            .fontSize(7)
            .fillColor('#aaaaaa')
            .text(
                'This ticket was generated by AI and does not replace physician assessment. No patient data is stored.',
                { align: 'center' }
            )

        doc.end()
    })
}
